### ISSUE TITLE
Ditch Arachas and get the card definition

### ISSUE THREAD

**Issue by Tri125** [GwentAPI/gwentapi#12]
Will allow to reduce our dependencies, support the different languages, and probably stabilise the Uuid once and for all. Will require a complete rewrite of db_setup and a breaking change to the API for the languages.

- [x] Stabilize UUID - that way the same card (with same data/version) stays the same.

- [x] Rewrite db_script in Go

- [x] API design to support multiple localization

- [x] db design to support multiple localization

- [ ] Finding a way to support multiple version of the same card.

**Comment by zhouzi** [comment]
I'm curious, where would you get the data if not crawling gwentdb.com?

**Comment by Tri125** [comment]
On gwentify.

**Comment by Tri125** [comment]
Done with 1102f3b.
Support for multiple version of the same card will be on its own issue, eventually.
